/**
 * Test-only in-process HTTPS server fixture. Lives under `test/`, outside `src/`, so it can never
 * ship in the production bundle. No key material is committed: a throwaway self-signed EC P-256
 * certificate (`CN=localhost`, SANs `DNS:localhost, IP:127.0.0.1`, valid one day) is generated by
 * `openssl` into a temp directory the first time a test asks for it, held in memory, and the
 * directory is removed immediately. Requires `openssl` on PATH (present on CI's ubuntu-latest and
 * in the dev container).
 */
import { execFileSync } from "node:child_process";
import { mkdtempSync, readFileSync, rmSync } from "node:fs";
import * as https from "node:https";
import type { RequestListener } from "node:http";
import { tmpdir } from "node:os";
import { join } from "node:path";

export interface TestCredentials {
  cert: string;
  key: string;
}

let cached: TestCredentials | undefined;

/** Generates (once per process) and returns the throwaway certificate and key. */
export function testCredentials(): TestCredentials {
  if (cached) return cached;
  const dir = mkdtempSync(join(tmpdir(), "denialdesk-tls-"));
  try {
    execFileSync(
      "openssl",
      [
        "req",
        "-x509",
        "-newkey",
        "ec",
        "-pkeyopt",
        "ec_paramgen_curve:prime256v1",
        "-nodes",
        "-subj",
        "/CN=localhost",
        "-addext",
        "subjectAltName=DNS:localhost,IP:127.0.0.1",
        "-days",
        "1",
        "-keyout",
        join(dir, "key.pem"),
        "-out",
        join(dir, "cert.pem"),
      ],
      { stdio: "ignore" },
    );
    cached = {
      cert: readFileSync(join(dir, "cert.pem"), "utf8"),
      key: readFileSync(join(dir, "key.pem"), "utf8"),
    };
  } finally {
    rmSync(dir, { recursive: true, force: true });
  }
  return cached;
}

/** The fixture certificate, for use as the transport's test-only `ca`. */
export function testCert(): string {
  return testCredentials().cert;
}

export interface TestServer {
  /** `https://localhost:<port>/` (a hostname, so the guarded `lookup` hook runs). */
  url: URL;
  /** `https://127.0.0.1:<port>/` (an IP literal, which bypasses `lookup`). */
  ipUrl: URL;
  port: number;
  close(): Promise<void>;
}

/**
 * Starts a throwaway HTTPS server on loopback with the generated certificate, running `onRequest`
 * for each request. `tlsOverrides` lets a test build a deliberately weak or restricted server (e.g.
 * `maxVersion: 'TLSv1.1'`) to prove the client refuses it.
 */
export async function startTestServer(
  onRequest: RequestListener,
  tlsOverrides: https.ServerOptions = {},
): Promise<TestServer> {
  const { cert, key } = testCredentials();
  const server = https.createServer({ cert, key, ...tlsOverrides }, onRequest);
  await new Promise<void>((resolve, reject) => {
    server.once("error", reject);
    server.listen(0, "127.0.0.1", () => resolve());
  });
  const address = server.address();
  if (!address || typeof address === "string") throw new Error("Test server has no port");
  return {
    url: new URL(`https://localhost:${address.port}/`),
    ipUrl: new URL(`https://127.0.0.1:${address.port}/`),
    port: address.port,
    close: () =>
      new Promise<void>((resolve, reject) => {
        server.closeAllConnections();
        server.close((err) => (err ? reject(err) : resolve()));
      }),
  };
}
