import ExcelJS from "exceljs";

/**
 * Builds well-formatted .xlsx workbooks for Insight standard reports (owner decision 2026-09-26:
 * "these reports must be well crafted in an Excel spreadsheet ... business people need to export
 * the data"). Every workbook gets an "About" cover sheet, then one or more data sheets with a
 * bold frozen header row, autofilter, sensible column widths, real numeric/date/percent cells,
 * and a totals row where meaningful. No merged cells in data areas. Text cells are sanitized
 * against formula injection before being written.
 */

const FORMULA_INJECTION = /^[\s]*[=+\-@＝＋－＠]/;

/**
 * Neutralizes a text value that a spreadsheet application could read as a formula (OWASP CSV/
 * formula injection). Mirrors the convention in `src/lib/csv/parse.ts`'s `csvCell`, applied here
 * to xlsx text cells instead of CSV text.
 */
export function sanitizeCellText(value: string): string {
  return FORMULA_INJECTION.test(value) ? `'${value}` : value;
}

export type ColumnType = "text" | "currency" | "percent" | "date" | "number";

export interface ColumnSpec {
  header: string;
  key: string;
  type: ColumnType;
  width?: number;
}

export interface SheetSpec {
  name: string;
  columns: ColumnSpec[];
  rows: Record<string, string | number | null>[];
  /** Values for the totals row, keyed by column key; omitted keys are left blank. */
  totals?: Record<string, string | number | null>;
}

export interface WorkbookAbout {
  reportName: string;
  practiceName: string;
  filtersApplied: string[];
  generatedAt: Date;
  /** User ID only — never a name, matching "no PHI in exports" (R-7.4.8). */
  generatedByUserId: string;
  definitions: { term: string; definition: string }[];
  caveats: string[];
}

const CURRENCY_FORMAT = '"$"#,##0.00;[Red]-"$"#,##0.00';
const PERCENT_FORMAT = "0.00%";
const DATE_FORMAT = "mm/dd/yyyy";

function cellValue(type: ColumnType, value: string | number | null): string | number | Date | null {
  if (value === null) return null;
  if (type === "text") return sanitizeCellText(String(value));
  if (type === "date") return new Date(`${value}T00:00:00Z`);
  // currency: convert integer cents to dollars only at write time (never stored as dollars elsewhere).
  if (type === "currency") return Number(value) / 100;
  return Number(value);
}

function numberFormat(type: ColumnType): string | undefined {
  if (type === "currency") return CURRENCY_FORMAT;
  if (type === "percent") return PERCENT_FORMAT;
  if (type === "date") return DATE_FORMAT;
  return undefined;
}

function addAboutSheet(workbook: ExcelJS.Workbook, about: WorkbookAbout) {
  const sheet = workbook.addWorksheet("About");
  sheet.columns = [{ width: 28 }, { width: 90 }];
  let row = 1;
  const heading = (text: string) => {
    const cell = sheet.getCell(row, 1);
    cell.value = sanitizeCellText(text);
    cell.font = { bold: true, size: 13 };
    row += 1;
  };
  const field = (label: string, value: string) => {
    sheet.getCell(row, 1).value = sanitizeCellText(label);
    sheet.getCell(row, 1).font = { bold: true };
    sheet.getCell(row, 2).value = sanitizeCellText(value);
    row += 1;
  };
  heading(about.reportName);
  row += 1;
  field("Practice", about.practiceName);
  field("Generated at", about.generatedAt.toISOString());
  field("Generated by (user ID)", about.generatedByUserId);
  field("Filters applied", about.filtersApplied.join("; ") || "None");
  row += 1;
  heading("Definitions");
  for (const { term, definition } of about.definitions) {
    sheet.getCell(row, 1).value = sanitizeCellText(term);
    sheet.getCell(row, 1).font = { bold: true };
    sheet.getCell(row, 2).value = sanitizeCellText(definition);
    row += 1;
  }
  row += 1;
  heading("Data caveats");
  for (const caveat of about.caveats) {
    sheet.getCell(row, 1).value = sanitizeCellText(`• ${caveat}`);
    sheet.mergeCells(row, 1, row, 2); // caveats are prose, not data — merging here is fine.
    sheet.getCell(row, 1).alignment = { wrapText: true };
    row += 1;
  }
}

function addDataSheet(workbook: ExcelJS.Workbook, spec: SheetSpec) {
  const sheet = workbook.addWorksheet(spec.name.slice(0, 31)); // Excel sheet-name limit.
  sheet.columns = spec.columns.map((c) => ({ header: c.header, key: c.key, width: c.width ?? 18 }));
  const headerRow = sheet.getRow(1);
  headerRow.font = { bold: true };
  headerRow.eachCell((cell) => {
    cell.fill = { type: "pattern", pattern: "solid", fgColor: { argb: "FFE8ECF1" } };
  });
  sheet.views = [{ state: "frozen", ySplit: 1 }];

  for (const row of spec.rows) {
    const values: Record<string, string | number | Date | null> = {};
    for (const column of spec.columns) {
      values[column.key] = cellValue(column.type, row[column.key] ?? null);
    }
    const added = sheet.addRow(values);
    for (const column of spec.columns) {
      const fmt = numberFormat(column.type);
      if (fmt) added.getCell(column.key).numFmt = fmt;
    }
  }

  if (spec.totals) {
    const values: Record<string, string | number | Date | null> = {};
    for (const column of spec.columns) {
      const raw = spec.totals[column.key];
      values[column.key] = raw === undefined ? null : cellValue(column.type, raw);
    }
    const totalsRow = sheet.addRow(values);
    totalsRow.font = { bold: true };
    for (const column of spec.columns) {
      const fmt = numberFormat(column.type);
      if (fmt) totalsRow.getCell(column.key).numFmt = fmt;
    }
  }

  sheet.autoFilter = {
    from: { row: 1, column: 1 },
    to: { row: 1, column: spec.columns.length },
  };
}

/** One workbook holding a single report's About sheet and its data sheet(s). */
export async function buildReportWorkbook(about: WorkbookAbout, sheets: SheetSpec[]): Promise<Buffer> {
  const workbook = new ExcelJS.Workbook();
  workbook.creator = "DenialDesk";
  workbook.created = about.generatedAt;
  addAboutSheet(workbook, about);
  for (const sheet of sheets) addDataSheet(workbook, sheet);
  return Buffer.from(await workbook.xlsx.writeBuffer());
}

/** The "All reports" workbook: one About sheet, then one data sheet per report. */
export async function buildAllReportsWorkbook(
  about: WorkbookAbout,
  reportSheets: SheetSpec[],
): Promise<Buffer> {
  return buildReportWorkbook(about, reportSheets);
}
