import ExcelJS from "exceljs";
import { isSuppressedCell, suppressedLabel, type SuppressedCell } from "./suppression";

/**
 * Builds well-formatted .xlsx workbooks for Insight standard reports (owner decision 2026-09-26:
 * "these reports must be well crafted in an Excel spreadsheet ... business people need to export
 * the data"). Every workbook gets an "About" cover sheet, then one or more data sheets with a
 * bold frozen header row, autofilter, sensible column widths, real numeric/date/percent cells,
 * and a totals row where meaningful. No merged cells in data areas. Text cells are sanitized
 * against formula injection before being written.
 */

const FORMULA_INJECTION = /^[\s]*[=+\-@＝＋－＠]/;

/**
 * Neutralizes a text value that a spreadsheet application could read as a formula (OWASP CSV/
 * formula injection). Mirrors the convention in `src/lib/csv/parse.ts`'s `csvCell`, applied here
 * to xlsx text cells instead of CSV text.
 */
export function sanitizeCellText(value: string): string {
  return FORMULA_INJECTION.test(value) ? `'${value}` : value;
}

export type ColumnType = "text" | "currency" | "percent" | "date" | "number";

export interface ColumnSpec {
  header: string;
  key: string;
  type: ColumnType;
  width?: number;
}

/**
 * A cell's value. `SuppressedCell` is a typed, explicit marker (R-8.7 small-cell suppression) —
 * never a string compared against the marker's display label — so a genuine value that happens to
 * read like the label text is never misread as suppressed, and vice versa.
 */
export type CellValue = string | number | null | SuppressedCell;

export interface SheetSpec {
  name: string;
  columns: ColumnSpec[];
  rows: Record<string, CellValue>[];
  /** Values for the totals row, keyed by column key; omitted keys are left blank. */
  totals?: Record<string, CellValue>;
  /** Shown instead of an empty data area (e.g. "No decided appeals in this period"). */
  emptyMessage?: string;
}

export interface WorkbookAbout {
  reportName: string;
  practiceName: string;
  filtersApplied: string[];
  generatedAt: Date;
  /** User ID only — never a name, matching "no PHI in exports" (R-7.4.8). */
  generatedByUserId: string;
  definitions: { term: string; definition: string }[];
  caveats: string[];
}

const CURRENCY_FORMAT = '"$"#,##0.00;[Red]-"$"#,##0.00';
const PERCENT_FORMAT = "0.00%";
const DATE_FORMAT = "mm/dd/yyyy";

function cellValue(type: ColumnType, value: CellValue): string | number | Date | null {
  if (value === null) return null;
  // Small-cell suppression (R-8.7): the marker is text regardless of the column's declared type
  // (currency/percent/number), so it never gets coerced into a number or a currency format.
  if (isSuppressedCell(value)) return sanitizeCellText(suppressedLabel());
  if (type === "text") return sanitizeCellText(String(value));
  if (type === "date") return new Date(`${value}T00:00:00Z`);
  // currency: convert integer cents to dollars only at write time (never stored as dollars elsewhere).
  if (type === "currency") return Number(value) / 100;
  return Number(value);
}

function numberFormat(type: ColumnType): string | undefined {
  if (type === "currency") return CURRENCY_FORMAT;
  if (type === "percent") return PERCENT_FORMAT;
  if (type === "date") return DATE_FORMAT;
  return undefined;
}

function addAboutSheet(workbook: ExcelJS.Workbook, about: WorkbookAbout) {
  const sheet = workbook.addWorksheet("About");
  sheet.columns = [{ width: 28 }, { width: 90 }];
  let row = 1;
  const heading = (text: string) => {
    const cell = sheet.getCell(row, 1);
    cell.value = sanitizeCellText(text);
    cell.font = { bold: true, size: 13 };
    row += 1;
  };
  const field = (label: string, value: string) => {
    sheet.getCell(row, 1).value = sanitizeCellText(label);
    sheet.getCell(row, 1).font = { bold: true };
    sheet.getCell(row, 2).value = sanitizeCellText(value);
    row += 1;
  };
  heading(about.reportName);
  row += 1;
  field("Practice", about.practiceName);
  field("Generated at", about.generatedAt.toISOString());
  field("Generated by (user ID)", about.generatedByUserId);
  field("Filters applied", about.filtersApplied.join("; ") || "None");
  row += 1;
  heading("Definitions");
  for (const { term, definition } of about.definitions) {
    sheet.getCell(row, 1).value = sanitizeCellText(term);
    sheet.getCell(row, 1).font = { bold: true };
    sheet.getCell(row, 2).value = sanitizeCellText(definition);
    row += 1;
  }
  row += 1;
  heading("Data caveats");
  for (const caveat of about.caveats) {
    sheet.getCell(row, 1).value = sanitizeCellText(`• ${caveat}`);
    sheet.mergeCells(row, 1, row, 2); // caveats are prose, not data — merging here is fine.
    sheet.getCell(row, 1).alignment = { wrapText: true };
    row += 1;
  }
  row += 1;
  sheet.getCell(row, 1).value = sanitizeCellText(
    "Contains confidential practice data; handle per your practice's policy.",
  );
  sheet.getCell(row, 1).font = { italic: true };
  sheet.mergeCells(row, 1, row, 2);
  sheet.getCell(row, 1).alignment = { wrapText: true };
}

function addDataSheet(workbook: ExcelJS.Workbook, spec: SheetSpec, sheetName: string) {
  const sheet = workbook.addWorksheet(sheetName);
  sheet.columns = spec.columns.map((c) => ({ header: c.header, key: c.key, width: c.width ?? 18 }));
  const headerRow = sheet.getRow(1);
  headerRow.font = { bold: true };
  headerRow.eachCell((cell) => {
    cell.fill = { type: "pattern", pattern: "solid", fgColor: { argb: "FFE8ECF1" } };
  });
  sheet.views = [{ state: "frozen", ySplit: 1 }];

  if (spec.rows.length === 0 && spec.emptyMessage) {
    const cell = sheet.getCell(2, 1);
    cell.value = sanitizeCellText(spec.emptyMessage);
    cell.font = { italic: true };
    sheet.autoFilter = { from: { row: 1, column: 1 }, to: { row: 1, column: spec.columns.length } };
    return;
  }

  for (const row of spec.rows) {
    const values: Record<string, string | number | Date | null> = {};
    for (const column of spec.columns) {
      values[column.key] = cellValue(column.type, row[column.key] ?? null);
    }
    const added = sheet.addRow(values);
    for (const column of spec.columns) {
      const raw = row[column.key] ?? null;
      if (isSuppressedCell(raw)) continue; // leave the suppression marker as plain text
      const fmt = numberFormat(column.type);
      if (fmt) added.getCell(column.key).numFmt = fmt;
    }
  }

  if (spec.totals) {
    const values: Record<string, string | number | Date | null> = {};
    for (const column of spec.columns) {
      const raw = spec.totals[column.key];
      values[column.key] = raw === undefined ? null : cellValue(column.type, raw);
    }
    const totalsRow = sheet.addRow(values);
    totalsRow.font = { bold: true };
    for (const column of spec.columns) {
      const raw = spec.totals[column.key] ?? null;
      if (isSuppressedCell(raw)) continue; // leave the suppression marker as plain text
      const fmt = numberFormat(column.type);
      if (fmt) totalsRow.getCell(column.key).numFmt = fmt;
    }
  }

  sheet.autoFilter = {
    from: { row: 1, column: 1 },
    to: { row: 1, column: spec.columns.length },
  };
}

/**
 * A unique, Excel-legal (<=31 char) sheet name for `name`, avoiding any name already in `used`.
 * Truncating independently derived names can produce identical prefixes (e.g. two "Appeal
 * outcomes by ..." sheets); this always resolves to a distinct name, numbering when it must.
 */
const SHEET_NAME_FORBIDDEN = /[*?:\\/[\]]/g;

export function uniqueSheetName(name: string, used: Set<string>): string {
  const base = name.replace(SHEET_NAME_FORBIDDEN, "-").slice(0, 31) || "Sheet";
  if (!used.has(base)) {
    used.add(base);
    return base;
  }
  for (let n = 2; ; n++) {
    const suffix = ` (${n})`;
    const candidate = base.slice(0, 31 - suffix.length) + suffix;
    if (!used.has(candidate)) {
      used.add(candidate);
      return candidate;
    }
  }
}

/** One workbook holding a single report's About sheet and its data sheet(s). */
export async function buildReportWorkbook(about: WorkbookAbout, sheets: SheetSpec[]): Promise<Buffer> {
  const workbook = new ExcelJS.Workbook();
  workbook.creator = "DenialDesk";
  workbook.created = about.generatedAt;
  addAboutSheet(workbook, about);
  const used = new Set<string>(["About"]);
  for (const sheet of sheets) addDataSheet(workbook, sheet, uniqueSheetName(sheet.name, used));
  return Buffer.from(await workbook.xlsx.writeBuffer());
}

/** The "All reports" workbook: one About sheet, then one data sheet per report. */
export async function buildAllReportsWorkbook(
  about: WorkbookAbout,
  reportSheets: SheetSpec[],
): Promise<Buffer> {
  return buildReportWorkbook(about, reportSheets);
}
