import type { Rule } from "./types";

// The only place legal deadlines, rates, and thresholds live (CLAUDE.md, R-15.6).
// Source for Florida values: docs/REQUIREMENTS.md §3.1 (checked 2026-09-26). Every rule stays
// verify: true until Florida healthcare counsel confirms it; only a human changes that flag.
// To change a value, add a new version with a new effectiveFrom and close the old one — never edit
// history, so older claims are judged by the rule in force at the time.

const FL_BOTH = ["fl_insurer", "fl_hmo"] as const;
const HMO_NOTE =
  "HMO values assumed to mirror § 627.6131 per REQUIREMENTS §3.1; confirm § 641.3155 subsections.";

export const catalog: Rule[] = [
  // Florida prompt pay — electronic claims (payer obligations)
  {
    id: "fl.promptpay.electronic.pay_or_contest",
    title: "Payer must pay, or notify that the claim is denied or contested",
    citation: "Fla. Stat. § 627.6131(4)(b); § 641.3155 (HMO)",
    regimes: [...FL_BOTH],
    value: 20,
    unit: "calendar_days",
    effectiveFrom: null,
    effectiveTo: null,
    verify: true,
    verifyNote: HMO_NOTE,
  },
  {
    id: "fl.promptpay.electronic.pay_or_deny",
    title: "Payer must pay or deny",
    citation: "Fla. Stat. § 627.6131(4)(e); § 641.3155 (HMO)",
    regimes: [...FL_BOTH],
    value: 90,
    unit: "calendar_days",
    effectiveFrom: null,
    effectiveTo: null,
    verify: true,
    verifyNote: HMO_NOTE,
  },
  {
    id: "fl.promptpay.electronic.uncontestable",
    title: "Failure to pay or deny creates an uncontestable obligation to pay",
    citation: "Fla. Stat. § 627.6131(4)(e); § 641.3155 (HMO)",
    regimes: [...FL_BOTH],
    value: 120,
    unit: "calendar_days",
    effectiveFrom: null,
    effectiveTo: null,
    verify: true,
    verifyNote: HMO_NOTE,
  },
  {
    id: "fl.promptpay.electronic.provider_response",
    title: "Provider must submit additional information requested on a contested claim",
    citation: "Fla. Stat. § 627.6131(4)(c)",
    regimes: [...FL_BOTH],
    value: 35,
    unit: "calendar_days",
    effectiveFrom: null,
    effectiveTo: null,
    verify: true,
    verifyNote: "Flagged ⚠️ VERIFY in REQUIREMENTS §3.1.",
  },
  // Florida prompt pay — paper claims
  {
    id: "fl.promptpay.paper.pay_or_contest",
    title: "Payer must pay, deny, or contest (paper claim)",
    citation: "Fla. Stat. § 627.6131(5)(b); § 641.3155 (HMO)",
    regimes: [...FL_BOTH],
    value: 40,
    unit: "calendar_days",
    effectiveFrom: null,
    effectiveTo: null,
    verify: true,
    verifyNote: HMO_NOTE,
  },
  {
    id: "fl.promptpay.paper.pay_or_deny",
    title: "Payer must pay or deny (paper claim)",
    citation: "Fla. Stat. § 627.6131(5); § 641.3155 (HMO)",
    regimes: [...FL_BOTH],
    value: 120,
    unit: "calendar_days",
    effectiveFrom: null,
    effectiveTo: null,
    verify: true,
    verifyNote: "Flagged ⚠️ VERIFY in REQUIREMENTS §3.1.",
  },
  {
    id: "fl.promptpay.paper.uncontestable",
    title: "Uncontestable obligation to pay (paper claim)",
    citation: "Fla. Stat. § 627.6131(5); § 641.3155 (HMO)",
    regimes: [...FL_BOTH],
    value: 140,
    unit: "calendar_days",
    effectiveFrom: null,
    effectiveTo: null,
    verify: true,
    verifyNote: "Flagged ⚠️ VERIFY in REQUIREMENTS §3.1.",
  },
  {
    id: "fl.promptpay.interest_rate",
    title: "Interest on overdue payments",
    citation: "Fla. Stat. § 627.6131 (interest provision; subsection to confirm)",
    regimes: [...FL_BOTH],
    value: 12,
    unit: "percent_per_year",
    effectiveFrom: null,
    effectiveTo: null,
    verify: true,
    verifyNote: "REQUIREMENTS §3.1: verify current rate and accrual start.",
  },
  // Timely filing (provider obligations)
  {
    id: "fl.timely_filing.initial",
    title: "Provider must submit the initial claim after the date of service",
    citation: "Fla. Stat. § 627.6131(2)",
    regimes: [...FL_BOTH],
    value: 6,
    unit: "months",
    effectiveFrom: null,
    effectiveTo: null,
    verify: true,
    verifyNote: "Subject to listed exceptions; flagged ⚠️ VERIFY in REQUIREMENTS §3.1.",
  },
  {
    id: "medicare.timely_filing",
    title: "Medicare claim must be filed after the date of service",
    citation: "42 CFR § 424.44(a)(1)",
    regimes: ["medicare"],
    value: 12,
    unit: "months",
    effectiveFrom: null,
    effectiveTo: null,
    verify: true,
  },
  // Appeals
  {
    id: "medicare.redetermination.receipt_presumption",
    title: "Notice of initial determination presumed received after its date",
    citation: "42 CFR § 405.942(a)(1)",
    regimes: ["medicare"],
    value: 5,
    unit: "calendar_days",
    effectiveFrom: null,
    effectiveTo: null,
    verify: true,
  },
  {
    id: "medicare.redetermination.filing_window",
    title: "Request redetermination after receipt of the initial determination",
    citation: "42 CFR § 405.942(a)",
    regimes: ["medicare"],
    value: 120,
    unit: "calendar_days",
    effectiveFrom: null,
    effectiveTo: null,
    verify: true,
  },
];
